stages:
  - build
  - test
  - deploy

build_application:
  stage: build
  script:
    - echo "Building App..."

test_application:
  stage: test
  before_script:
    - echo "Starting application tests"
  script:
    - echo "Running tests..."

deploy_to_homologation:
  stage: deploy
  before_script:
    - echo "Deploying to homologation environment"
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  script:
    - ssh $SSH_USER@$SSH_HOST "git config --global --add safe.directory /opt/ENX/shortner_url"
    - ssh $SSH_USER@$SSH_HOST "cd /opt/ENX/shortner_url && sudo git pull"
    - ssh $SSH_USER@$SSH_HOST "cd /opt/ENX/shortner_url && sudo docker-compose down"
    - ssh $SSH_USER@$SSH_HOST "cd /opt/ENX/shortner_url && sudo docker-compose up --build -d"
    - ssh $SSH_USER@$SSH_HOST "cd /opt/ENX/shortner_url && sudo docker-compose ps"
  only:
    - main