stages:
  - build
  - test
  - deploy

build_application:
  stage: build
  script:
    - echo "Building App..."

test_application:
  stage: test
  before_script:
    - echo "Starting application tests"
  script:
    - echo "Running tests..."

deploy_to_homologation:
  stage: deploy
  before_script:
    - echo "Deploying to homologation environment"
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY_HOMOLOG")
    - mkdir -p ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  script:
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin registry.ntsec.com.br
    - ssh $SSH_USER@$SSH_HOST_HOMOLOG "cd /opt/template-test && sudo docker pull registry.ntsec.com.br"
    - ssh $SSH_USER@$SSH_HOST_HOMOLOG "cd /opt/template-test && sudo docker compose up -d"
    - ssh $SSH_USER@$SSH_HOST_HOMOLOG "cd /opt/template-test && sudo docker compose ps"
  only:
    - develop

deploy_to_production:
  stage: deploy
  before_script:
    - echo "Deploying to production environment"
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY_PROD")
    - mkdir -p ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  script:
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin registry.ntsec.com.br
    - ssh $SSH_USER@$SSH_HOST_PROD "cd /opt/template-test && sudo docker pull registry.ntsec.com.br"
    - ssh $SSH_USER@$SSH_HOST_PROD "cd /opt/template-test && sudo docker compose up -d"
    - ssh $SSH_USER@$SSH_HOST_PROD "cd /opt/template-test && sudo docker compose ps"
  when: manual
  # enviroment:
  #   name: production
  #   url:
  only:
    - main
  # after_script:
  #   - >
  #     if [ $? -ne 0 ]; then
  #       echo "Deployment failed, rolling back..."
  #       docker-compose down
  #       docker-compose up -d --no-deps --build previous_version
  #     fi
