stages:
  - build
  - test
  - deploy

build_docker_image:
  stage: build
  before_script:
    - echo "Starting the job - Build Docker image"
  script:
    - echo "Building docker images"

test_application:
  stage: test
  before_script:
    - echo "Starting application tests"
  script:
    - echo "Running tests..."

deploy_application:
  stage: deploy
  script:
    - echo "Deploying our application - test."
