version: '3.8'

services:
  server:
    container_name: enx-server
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - '8000:8000'
    restart: unless-stopped
    depends_on:
      - db

  client:
    container_name: enx-client
    build:
      context: ./client
    env_file:
      - ./client/.env
    ports:
      - '3000:3000'
    restart: unless-stopped
    links:
      - server

  db:
    container_name: enx-db
    image: postgres:14-alpine
    env_file:
      - ./db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped

volumes:
  postgres_data:
