apiVersion: apps/v1
kind: Deployment
metadata:
  name: enx-server
spec:
  selector:
    matchLabels:
      app: enx-server
  template:
    metadata:
      labels:
        app: enx-server
    spec:
      containers:
        - name: enx-server
          image: gusdevr/enx-server:v1.0
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: env-volume
              mountPath: server/.env
              subPath: .env
      volumes:
        - name: env-volume
          configMap:
            name: env-configmap
            items:
              - key: .env
                path: .env
---
apiVersion: v1
kind: Service
metadata:
  name: enx-client-service
spec:
  selector:
    app: enx-client-service
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
